[package]
name = "class-5"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "race"
path = "src/bin/race.rs"

[[bin]]
name = "fixed"
path = "src/bin/fixed.rs"

[dependencies]
anyhow = "1.0.100"
eyre = "0.6.12"
tokio = { version = "1.48.0", features = ["full"] }
